'use strict';

exports.ERR_INVALID_AGENCY_NAME = 'ERR_INVALID_AGENCY_NAME';
exports.ERR_INVALID_ROUTE_CODE = 'ERR_INVALID_ROUTE_CODE';
exports.ERR_INVALID_DIRECTION_CODE = 'ERR_INVALID_DIRECTION_CODE';
exports.ERR_INVALID_STOP_CODE = 'ERR_INVALID_STOP_CODE';